# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-13 06:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cardetails',
            fields=[
                ('id', models.IntegerField(db_column='id', primary_key=True, serialize=False)),
                ('caryear', models.IntegerField(db_column='CarYear')),
                ('carnum', models.IntegerField(db_column='CarNum')),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
                ('jalbumlink', models.CharField(blank=True, db_column='JAlbumLink', max_length=100, null=True)),
                ('chapterid', models.IntegerField(blank=True, db_column='ChapterID', null=True)),
            ],
            options={
                'db_table': 'CarDetails',
            },
        ),
        migrations.CreateModel(
            name='Carimages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carcategory', models.CharField(db_column='CarCategory', max_length=30)),
                ('caryear', models.IntegerField(db_column='CarYear')),
                ('carnum', models.IntegerField(db_column='CarNum')),
                ('imagenum', models.IntegerField(db_column='ImageNum')),
                ('imagepath', models.CharField(blank=True, db_column='ImagePath', max_length=50, null=True)),
                ('description', models.TextField(blank=True, db_column='Description', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
            ],
            options={
                'db_table': 'CarImages',
            },
        ),
        migrations.CreateModel(
            name='Chapters',
            fields=[
                ('chapterid', models.IntegerField(db_column='ChapterID', primary_key=True, serialize=False)),
                ('chaptername', models.CharField(blank=True, db_column='ChapterName', max_length=50, null=True)),
                ('description', models.CharField(blank=True, db_column='Description', max_length=150, null=True)),
                ('superchapterid', models.IntegerField(blank=True, db_column='SuperChapterID', null=True)),
                ('imagepath', models.CharField(blank=True, db_column='ImagePath', max_length=150, null=True)),
            ],
            options={
                'db_table': 'Chapters',
            },
        ),
        migrations.CreateModel(
            name='CopyCardetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, db_column='Category', max_length=30, null=True)),
                ('year', models.CharField(blank=True, db_column='Year', max_length=10, null=True)),
                ('carnum', models.CharField(blank=True, db_column='CarNum', max_length=10, null=True)),
                ('title', models.CharField(blank=True, db_column='Title', max_length=30, null=True)),
                ('content', models.TextField(blank=True, db_column='Content', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
            ],
            options={
                'db_table': 'Copy_CarDetails',
            },
        ),
    ]
