# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 23:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EB', '0002_cardetailsupdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalImages',
            fields=[
                ('imageurl', models.CharField(db_column='ImageUrl', max_length=100)),
                ('imagecaption', models.CharField(blank=True, db_column='ImageCaption', max_length=200, null=True)),
                ('imageid', models.AutoField(db_column='ImageID', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Historical_Images',
            },
        ),
        migrations.CreateModel(
            name='Historicalinformation',
            fields=[
                ('sectionid', models.CharField(db_column='SectionID', max_length=50, primary_key=True, serialize=False)),
                ('sectionorder', models.IntegerField(db_column='SectionOrder')),
                ('sectiontitle', models.CharField(blank=True, db_column='SectionTitle', max_length=50, null=True)),
                ('sectiontext', models.TextField(blank=True, db_column='SectionText', null=True)),
                ('createdby', models.CharField(blank=True, db_column='CreatedBy', max_length=50, null=True)),
                ('createdate', models.DateTimeField(blank=True, db_column='CreateDate', null=True)),
                ('lastupdatedate', models.DateTimeField(blank=True, db_column='LastUpdateDate', null=True)),
            ],
            options={
                'db_table': 'HistoricalInformation',
            },
        ),
        migrations.DeleteModel(
            name='CopyCardetails',
        ),
        migrations.RenameField(
            model_name='cardetails',
            old_name='id',
            new_name='carid',
        ),
        migrations.RemoveField(
            model_name='carimages',
            name='id',
        ),
        migrations.AddField(
            model_name='chapters',
            name='url',
            field=models.CharField(blank=True, db_column='url', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='cardetails',
            name='chapterid',
            field=models.ForeignKey(db_column='ChapterID', on_delete=django.db.models.deletion.CASCADE, to='EB.Chapters'),
        ),
        migrations.AlterField(
            model_name='cardetailsupdate',
            name='carid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB.Cardetails'),
        ),
        migrations.AlterField(
            model_name='carimages',
            name='imagenum',
            field=models.IntegerField(db_column='ImageNum', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='chapters',
            name='superchapterid',
            field=models.ForeignKey(db_column='SuperChapterID', on_delete=django.db.models.deletion.CASCADE, to='EB.Chapters'),
        ),
        migrations.AddField(
            model_name='historicalinformation',
            name='chapterid',
            field=models.ForeignKey(db_column='ChapterID', on_delete=django.db.models.deletion.CASCADE, to='EB.Chapters'),
        ),
        migrations.AddField(
            model_name='historicalimages',
            name='sectionid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EB.Historicalinformation'),
        ),
    ]
