# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-24 01:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EB', '0003_auto_20151217_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardetailsupdate',
            name='carid',
            field=models.ForeignKey(db_column='CarID', on_delete=django.db.models.deletion.CASCADE, to='EB.Cardetails'),
        ),
        migrations.AlterField(
            model_name='historicalimages',
            name='sectionid',
            field=models.ForeignKey(db_column='SectionID', on_delete=django.db.models.deletion.CASCADE, to='EB.Historicalinformation'),
        ),
    ]
